scoreboard:
  title: '&b&lPvp Up'
  lines: # reverse
    lobby:
      - '&emc.server.net'
      - '&a'
      - '&fMuertes: &c%pvpup_deaths%'
      - '&fBajas: &e%pvpup_kills%'
      - '&7Estadisticas'
      - '&e'
      - '&fMonedas: &e%pvpup_coins%'
      - '&f'
      - '&fRango: &c¡Adquierelo!'
      - '&f¡Hola! &b%pvpup_name%'
    match:
      - '&emc.server.net'
      - '&c'
      - '&fMuertes: &c%pvpup_deaths%'
      - '&fBajas: &e%pvpup_kills%'
      - '&a'
      - '&fNecesario: &6%pvpup_next_level_points% punto'
      - '&fSiguiente: &dNivel %pvpup_next_level%'
      - '&fPuntos: &a%pvpup_points%'
      - '&fActual: &eNivel %pvpup_current_level%'
      - '&7Estadisticas'
      - '&f'
      - '&fRango: &c¡Adquierelo!'
      - '&f¡Hola &b%pvpup_name%&f!'

messages:
  PLAYER_DEATH_WITHOUT_KILLER: '&c{%0}&7 was slain.'
  PLAYER_DEATH_WITH_KILLER: '&c{%0}&7 was slain by &a{%1}'
  LEVELS_MENU_ITEM_REACHED: '&f&oNivel {%0}&r&7 - &aAlcanzado'
  LEVELS_MENU_ITEM_PROGRESS: '&f&oNivel {%0}&r&7 - &eEn progreso'
  LEVELS_MENU_ITEM_LOCKED: '&f&oNivel {%0}&r&7 - &cNo alcanzado'
  LEVELS_MENU_ITEM_LORE_REACHED: "&d\n&7Puntos necesarios: &b{%0} puntos\n&a\n&7Este nivel contiene:\n&f{%1}\n&7\n&aYa haz alcanzado este nivel"
  LEVELS_MENU_ITEM_LORE_PROGRESS: "&d\n&7Puntos necesarios: &b{%0} puntos\n&7Actualmente tienes: &b{%2}\n&a\n&7Este nivel contiene:\n&f{%1}\n&7\n&eNecesitas {%3} puntos para alcanzar este nivel"
  LEVELS_MENU_ITEM_LORE_LOCKED: "&d\n&7Puntos necesarios: &b{%0} puntos\n&7Actualmente tienes: &b{%2}\n&a\n&7Este nivel contiene:\n&f{%1}\n&7\n&cAlcanza el nivel anterior para\n&ccomenzar con este nivel"
  WOOD_AXE: 'Hacha de madera'